Feature/switch component
tecsinapse/ui-kit pull request #144
Opened 2021-02-15 13:45 UTC by ryancarloscorrea

Adicionado: Button Group, Drawer re-estilizado, Switch

2021-02-15 21:02 UTC, dennervidal requested changes
verificar comentarios e aplicar correções.

2021-02-15 21:02 UTC, dennervidal commented on packages/ui-kit/src/components/Switch/Switch.d.ts
> +  on?: (e: object) => void;
chamar funções handler (on/off), só de onChange.
quando for true, é on, quando for false é off.

2021-02-15 23:49 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/Drawer.d.ts
> +  srcLogo?: string;
feito.

2021-02-16 17:25 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +      color: '#f99f1f',
feito.

2021-02-16 17:39 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +        backgroundColor: '#F29A1E',
feito

2021-02-16 17:54 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +              <Icon path={mdiMenuDown} color="#949494" size={1} />
feito.

2021-02-16 17:54 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +            colorTextPrimary: '#132',
feito.

2021-02-16 18:32 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Switch/Switch.d.ts
> +  label1?: string;
feito

2021-02-16 18:40 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +      backgroundColor: children && open ? '#78787A' : '#F0F0F0',
feito

2021-02-26 19:22 UTC, dennervidal approved these changes
@ryancarloscorrea depois remova o yarn.lock que ficou na pasta packages/ui-kit, o unico lockfile que deve existir no proejto é da raiz

2021-02-26 19:22 UTC, dennervidal commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +const useStyles = (depth, children, open) =>
@ryancarloscorrea pelo que entendi não há necessidade de passar o children aqui, pq não é usado. Vou aprovar o merge mas retire na sua feature atual.

2021-02-26 19:22 UTC, dennervidal commented on packages/ui-kit/stories/Menu/Drawer.story.tsx
> +    src: 'https://www.facom.ufms.br/wp-content/uploads/2019/05/ts-fundo-claro.png',
coloque aqui uma imagem de maior resolução, esse logo não é mais utilizado.

exemplo: https://www.tecsinapse.com.br/wp-content/themes/tecsinapse/img/logo.svg

2021-02-26 19:23 UTC, merged

2021-03-01 11:50 UTC, ryancarloscorrea commented on packages/ui-kit/src/components/Menu/Drawer/MenuItem/MenuItem.js
> +const useStyles = (depth, children, open) =>
feito.

2021-03-01 11:51 UTC, ryancarloscorrea commented on packages/ui-kit/stories/Menu/Drawer.story.tsx
> +    src: 'https://www.facom.ufms.br/wp-content/uploads/2019/05/ts-fundo-claro.png',
feito.