Adicionei uma prop no AdvancedFilters para alterar o maxwidth do drawer dos filtros
tecsinapse/ui-kit pull request #163
Opened 2021-04-19 18:09 UTC by lucaspr98

2021-04-19 20:34 UTC, dennervidal requested changes
no geral os testes estão quebrando, revisar os pontos citados

2021-04-19 20:34 UTC, dennervidal commented on packages/ui-kit/src/components/AutoComplete/AutoComplete.d.ts
> +  id: any;
@lucaspr98 aqui resetou o valuesprops pra any

2021-04-19 20:34 UTC, dennervidal commented on packages/table/src/Table/AdvancedFilters/AdvancedFilters.js
> +  console.log(customAdvancedFilters.drawerWidth);
remover log

2021-04-19 20:34 UTC, dennervidal commented on packages/table/src/Table/AdvancedFilters/AdvancedFilters.js
> +                         }) => {
configurar prettier pra ajustar esse espaçamento aqui

2021-04-19 20:34 UTC, dennervidal commented on packages/table/src/Table/AdvancedFilters/AdvancedFilters.js
> +    maxWidth = mobile ? '100%' : advancedFilters.drawerWidth ?
evitar aninhamento de ternários, quebrar em outros condicionais e padronizar de onde vai vir o default caso não exista esse valor (dar preferencia p/ optional chaining obj?.property)

2021-04-20 15:43 UTC, lucaspr98 commented
Ajustes feitos

2021-05-19 17:31 UTC, merged