feat: [ui-kit] Checkbox
tecsinapse/ui-kit pull request #168
Opened 2021-07-07 18:04 UTC by guilhermebrrrs

Criado componente checkbox.

2021-07-08 14:53 UTC, dennervidal requested changes

2021-07-08 14:53 UTC, dennervidal commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +  labelPlacement: PropTypes.string,
ajustar a mesma proptype como sugerido no radio button

2021-07-08 14:53 UTC, dennervidal commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +  const [check, setCheck] = useState(checked)
controle externo não funciona?

2021-07-08 14:53 UTC, dennervidal commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +        <Check
Verificar questão das variantes de cores como no radio button

2021-07-19 19:11 UTC, guilhermebrrrs commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +  labelPlacement: PropTypes.string,
Prop ajustada

2021-07-19 19:12 UTC, guilhermebrrrs commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +  const [check, setCheck] = useState(checked)
Não consegui mudar o valor do checked do Checkbox por controle externo.

2021-07-19 19:13 UTC, guilhermebrrrs commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +        <Check
Ajustada prop color do componente

2021-07-21 14:12 UTC, dennervidal requested changes

2021-07-21 14:12 UTC, dennervidal commented on packages/ui-kit/src/components/Checkbox/Checkbox.js
> +  const [check, setCheck] = useState(checked)
você precisa criar uma assinatura customizada, como por exemplo no design system.
receba uma função e um booleano para lidar com as trocas de valores, ai poderia ser assim:

`
  onChange,
  checked
...
  const handleChange = (value: boolean) => onChange(value);
`

2022-10-31 21:31 UTC, closed without merging